dist: trusty
sudo: required
language: c

addons:
  apt:
    packages:
      - rpm

compiler:
  - clang
  - gcc

env:
  - TARGET=distcheck
  - TARGET=dist-srpm

matrix:
  exclude:
    - compiler: clang
      env: TARGET=dist-srpm

before_script: ./autogen.sh

script:
  - ./build-aux/travis-build.sh
  - ./build-aux/travis-deploy.sh
